name: Build 7z-zstd Dark x64 binaries
on:
  push:
    branches:
      - main
      - 7z-zstd
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        #arch: [ x64, x64_x86, x64_arm64 ]
        arch: [ x64, x64_arm64 ]
        include:
          - arch: x64
            platform: x64
          #- arch: x64_x86
          #  platform: x86
          - arch: x64_arm64
            platform: arm64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build ${{ matrix.arch }}
        shell: cmd
        run: |
          build.cmd ${{ matrix.platform }}

      - name: Archive artifact ${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: Dark7z-zstd ${{ matrix.platform }}
          path: ${{ matrix.platform }}-bin
